"""Initial migration - create users and tasks tables

Revision ID: 001_initial
Revises:
Create Date: 2026-01-04 07:47:00.000000

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create users table
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("email", sa.VARCHAR(), nullable=False),
        sa.Column("hashed_password", sa.VARCHAR(), nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
        sa.Column("is_admin", sa.BOOLEAN(), nullable=True),
        sa.Column("avatar_url", sa.VARCHAR(), nullable=True),
        sa.Column("last_login", sa.DATETIME(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)

    # Create tasks table with all current fields
    op.create_table(
        "tasks",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("title", sa.VARCHAR(), nullable=False),
        sa.Column("description", sa.VARCHAR(), nullable=False),
        sa.Column(
            "state",
            sa.VARCHAR(length=11),
            nullable=False,
        ),
        sa.Column("due_date", sa.VARCHAR(), nullable=True),
        sa.Column("reward", sa.VARCHAR(), nullable=True),
        sa.Column(
            "created_at",
            sa.VARCHAR(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.VARCHAR(), nullable=True),
        sa.Column("completed_at", sa.VARCHAR(), nullable=True),
        sa.Column("created_by", sa.INTEGER(), nullable=False),
        sa.Column(
            "assignment_type",
            sa.Enum("any", "some", "one", name="assignmenttype"),
            nullable=False,
        ),
        sa.Column("assigned_to", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["assigned_to"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_id"), "tasks", ["id"], unique=False)
    op.create_index(op.f("ix_tasks_title"), "tasks", ["title"], unique=False)

    # Create association table for many-to-many relationship
    op.create_table(
        "task_assigned_users",
        sa.Column("task_id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("task_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_assigned_users")
    op.drop_index(op.f("ix_tasks_title"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
