"""Add indexes to task foreign key columns

Revision ID: 0996a25c0866
Revises: 001_initial
Create Date: 2026-01-04 09:46:15.940824

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '0996a25c0866'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add index to created_by column
    op.create_index('ix_tasks_created_by', 'tasks', ['created_by'], unique=False)
    # Add index to assigned_to column
    op.create_index('ix_tasks_assigned_to', 'tasks', ['assigned_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove index from created_by column
    op.drop_index('ix_tasks_created_by', table_name='tasks')
    # Remove index from assigned_to column
    op.drop_index('ix_tasks_assigned_to', table_name='tasks')
    # ### end Alembic commands ###
