"""Add task assignment and creator tracking

Revision ID: ade43a5b5e3a
Revises: 001_initial
Create Date: 2026-01-04 07:04:07.189215

"""

# revision identifiers, used by Alembic.
revision = "ade43a5b5e3a"
down_revision = "001_initial"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration is now a no-op since the initial migration already creates
    # the tables with the correct structure including assignment and creator tracking
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration is now a no-op since the initial migration already creates
    # the tables with the correct structure including assignment and creator tracking
    pass
    # ### end Alembic commands ###
