"""Add task assignment and creator tracking

Revision ID: ade43a5b5e3a
Revises:
Create Date: 2026-01-04 07:04:07.189215

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ade43a5b5e3a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite, we need to recreate the table with the new columns

    # Create new tasks table with assignment fields
    op.create_table(
        "tasks_new",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("title", sa.VARCHAR(), nullable=False),
        sa.Column("description", sa.VARCHAR(), nullable=False),
        sa.Column("state", sa.VARCHAR(length=11), nullable=False),
        sa.Column("due_date", sa.VARCHAR(), nullable=True),
        sa.Column("reward", sa.VARCHAR(), nullable=True),
        sa.Column(
            "created_at",
            sa.VARCHAR(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.VARCHAR(), nullable=True),
        sa.Column("completed_at", sa.VARCHAR(), nullable=True),
        sa.Column("created_by", sa.INTEGER(), nullable=False),
        sa.Column(
            "assignment_type",
            sa.Enum("any", "some", "one", name="assignmenttype"),
            nullable=False,
        ),
        sa.Column("assigned_to", sa.INTEGER(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["assigned_to"], ["users.id"]),
    )

    # Copy data from old table to new table
    op.execute(
        "INSERT INTO tasks_new "
        "(id, title, description, state, due_date, reward, created_at, "
        "started_at, completed_at, created_by, assignment_type) "
        "SELECT id, title, description, state, due_date, reward, created_at, "
        "started_at, completed_at, 1, 'any' FROM tasks"
    )

    # Drop old table and rename new one
    op.drop_table("tasks")
    op.rename_table("tasks_new", "tasks")

    # Recreate indexes
    op.create_index(op.f("ix_tasks_id"), "tasks", ["id"], unique=False)
    op.create_index(op.f("ix_tasks_title"), "tasks", ["title"], unique=False)

    # Create association table for many-to-many relationship
    op.create_table(
        "task_assigned_users",
        sa.Column("task_id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("task_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_assigned_users")
    op.drop_constraint("fk_tasks_assigned_to", "tasks", type_="foreignkey")
    op.drop_constraint("fk_tasks_created_by", "tasks", type_="foreignkey")
    op.drop_column("tasks", "assigned_to")
    op.drop_column("tasks", "assignment_type")
    op.drop_column("tasks", "created_by")
    # ### end Alembic commands ###
